version: '2.4'

networks:
  main-net:
    external:
      name: ed2k_main-net

services:
  application:
    image: ${PROJECT}:${PROJECT_VERSION}
    ports:
      - "5000:5000"
    env_file:
      - local.env
    environment:
      FLASK_ENV: development
      VIRTUAL_HOST: kafka-producer-tool.localhost, kafka-producer-tool.*
      VIRTUAL_PORT: 5000
    networks:
      - main-net
    volumes:
      - '../src/:/code:delegated'
    # depends_on:
    #   - kafka
  
  shell:
    extends:
      service: application
    entrypoint: ["bash"]

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9093:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.2.2
    container_name: redpanda-console
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      CONFIG_FILEPATH: /etc/redpanda/redpanda-config.yaml
      VIRTUAL_HOST: redpanda-console.localhost, redpanda-console.*
      VIRTUAL_PORT: 8080
    volumes:
      - ./redpanda-config.yaml:/etc/redpanda/redpanda-config.yaml:ro  # ✅ Mount config file
    networks:
      - main-net
    # depends_on:
    #   - zookeeper
    #   - kafka
    #   - kafka-schema-registry
    #   - kafka-rest-proxy
    labels:
      ed2k.type: admin-util
