version: '2.4'

networks:
  main-net:
    external:
      name: ed2k_main-net

services:
  application:
    image: ${PROJECT}:${PROJECT_VERSION}
    ports:
      - "5000:5000"
    env_file:
      - local.env
    environment:
      FLASK_ENV: development
      VIRTUAL_HOST: kafka-producer-tool.localhost, kafka-producer-tool.*
      VIRTUAL_PORT: 5000
    networks:
      - main-net
    volumes:
      - '../src/:/code:delegated'
    # depends_on:
    #   - kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9093:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
